### ISSUE TITLE
Improve overview loading speed

### ISSUE THREAD

**Issue by afollestad** [afollestad/impression#240]
A method of caching the overview albums is needed. It would need to store a path and name.

A way of updating when new albums exist is needed.

**Comment by yazeed44** [comment]
Why not use Glide and RoboSpice?

Checkout these two files i wrote for a similar functionality
https://github.com/yazeed44/MultiImagePicker/blob/master/library/src/main/java/net/yazeed44/imagepicker/ui/AlbumsFragment.java

https://github.com/yazeed44/MultiImagePicker/blob/master/library/src/main/java/net/yazeed44/imagepicker/util/Util.java

**Comment by plusCubed** [comment]
Speed should be fine now.
