### ISSUE TITLE
Weirdness after rotating and going back to MainActivity

### ISSUE THREAD

**Issue by plusCubed** [afollestad/impression#241]
1. Duplicate images (sometimes)
2. Transition not working
3. Sometimes theming doesn't get applied to the toolbar and navigation bar (see screenshot).

![rsz_screenshot_2015-02-05-16-33-47](https://cloud.githubusercontent.com/assets/1820165/6070780/1b2de5c0-ad55-11e4-8532-2b4dbe435500.png)

**Comment by ViswanathL** [comment]
Unable to produce the issue. Which device you have used

**Comment by plusCubed** [comment]
Fixed.
