### ISSUE TITLE
SDK Update to M - Preview

### ISSUE THREAD

**Issue by VirusThePanda** [afollestad/impression#284]
I noticed that this wasn't updated to M Preview. Do you think this should be done for any possible members in the community that have M?

**Comment by afollestad** [comment]
No, targeting 'M' will only work on M Preview devices, and nothing else. Not even the official M build when it's ready. 

I wouldn't advise doing so unless you were testing an M specific feature, that's what the preview is for after all.

**Comment by VirusThePanda** [comment]
Ah, okay. That makes sense and I didn't know that.
