### ISSUE TITLE
Cast Support (nanoHTTPD) + Android For Work

### ISSUE THREAD

**Issue by VirusThePanda** [afollestad/impression#295]
I just realised that some people might wanna use Impression for work purposes, similar to how some companies use Google Photos for this. I also thought of this while working on the nanoHTTPD Cast sample app for Impression. But I think it would be a good idea if possible, we could add another feture to cast for presentations. So the caster can draw on the image and the Cast will update and show it. (Kinda like how you can scroll on cast and it'll show the next picture). Could this be possible? Might be a good feature for work.

**Comment by afollestad** [comment]
That would be cool.

Btw, if you work on the Chromecast feature, there is another issue for that too: https://github.com/afollestad/impression/issues/190

**Comment by VirusThePanda** [comment]
I'll be working on it. Making the sample app to send you first to check and
see if it will actually work. If it does, I'll make a class inside of
Impression and send thst to you as well.

**Comment by afollestad** [comment]
Quite a lot, yeah, but I can handle that when the time comes :)

**Comment by afollestad** [comment]
Oops commented on the wrong issue lol.

Awesome!

**Comment by VirusThePanda** [comment]
Did you already put in code for Work? When I made an APK through Studio, it
appeared in both my normal and work (Test DPC) profiles.

**Comment by plusCubed** [comment]
@VirusThePanda There isn't anything related to Android for Work added that I know of.

**Comment by VirusThePanda** [comment]
Hmmm...must be a standard thing with Debug builds. Okay, thanks.
