### ISSUE TITLE
Implement Mike Penz's MaterialDrawer library

### ISSUE THREAD

**Issue by afollestad** [afollestad/impression#296]
The current drawer implementation I added when Impression first started is a bit outdated. Especially the account chooser.

We'd be much better off with [MaterialDrawer](https://github.com/mikepenz/MaterialDrawer).

**Comment by VirusThePanda** [comment]
I was just thinking of this. But wouldn't we have to re do many of the
classes that lead from the navigation drawer?

**Comment by afollestad** [comment]
Quite a lot, yeah, but I can handle that when the time comes :)

**Comment by plusCubed** [comment]
The navigation drawer is simple enough that I think it should be fine with the NavigationView from the design support library - haven't used it in a while, but I believe it's possible to have a custom header view for account switching (not a fan of the one in MaterialDrawer - missing animations and such).

**Comment by afollestad** [comment]
That sounds good to me
