### ISSUE TITLE
F-Droid version does not work

### ISSUE THREAD

**Issue by M2ck** [afollestad/impression#322]
Thanks for F-Droid support but unfortunately this version does not work, I get this error:

![unnamed9t3hx1yh](https://cloud.githubusercontent.com/assets/6850125/12089930/287b1022-b2ea-11e5-9d31-c69b837b5211.png)

**Comment by afollestad** [comment]
I didn't submit it to F-Droid.

**Comment by M2ck** [comment]
However your app is available on this store [Impression detail page](https://f-droid.org/repository/browse/?fdfilter=Impression&fdid=com.afollestad.impression)
@krt16s you are member of F-Droid team, could you give more explanation please?

**Comment by afollestad** [comment]
@M2ck no one here did, someone elsewhere must've.

They stripped non-open source components which causes the crash, so it won't be fixed for F-Droid. You'll need the Google Play version.

**Comment by M2ck** [comment]
@afollestad don't worry I know. 
It seems that was released by F-Droid, but I don't understand what interest to release consciously a buggy build.

Yeah but Google Play version requires Google+ account.
Maybe could you update APK available on Github? I will much appreciate.

**Comment by afollestad** [comment]
@M2ck the Google Play version is identical to the GitHub version.

Google Play Services is used not only for upcoming Chromecast integration, but also upcoming Google Photos integration. It can't be removed.

**Comment by krt16s** [comment]
I added the build yesterday, indeed. It worked okay on my device when used in explorer mode and I wanted to save the recipe for my personal use, but since other reported it worked fine for them, I enabled the build. However, I really tried to make sure in the description, not to bug upstream about any issues that are not present in official builds. I am REALLY sorry for this, @afollestad.

@M2ck: Please read the description. Not only for not to bug upstream, but also for a workaround for your problem....

**Comment by M2ck** [comment]
@krt16s as I said above I read the description but too late, I'm sorry.
Even with the workaround I get a message error but yes it "works".

Anyway sorry to having bother you guys, it's just that I was not expecting it.

**Comment by Airon90** [comment]
@krt16s @M2ck What about forking and maintain a version for the F-Droid community? I'm not a coder but I think that by now it just needs to remove some code (correctly :P).

**Comment by afollestad** [comment]
@Airon90 Impression is nowhere near a state where it should be published. It's currently only in a beta channel on Google Play. Most of the new features are not done, and there's lots of bugs.

**Comment by afollestad** [comment]
@krt16s is there anyway to remove my app from F-Droid? People continue to report the same bug despite the fact that the description there says not to.

**Comment by krt16s** [comment]
I can move it to our archive and remove links to your github page. I hope that helps... sorry for the trouble :( 

@Airon90: I rather have someone contributing code to upstream to provide a free build flavor... If there is a fork in progress, I will happily add it to f-droid, but i dont have the time not the experience to maintain or contribute to the fork... f-droid keeps me more than busy.
