### ISSUE TITLE
Error on startup.  App unusable on OxygenOS (5.1.1)

### ISSUE THREAD

**Issue by mrbar42** [afollestad/impression#325]
The app was installed through f-droid on OxygenOS 2.1.3 that is based on 5.1.1 (now isn't that tbe weirdest combination) 

The app won't crash,  but it shows this error and no photos are presented 

![screenshot_2016-01-07-13-31-15](https://cloud.githubusercontent.com/assets/12373774/12169711/2b1c8620-b543-11e5-8400-3bec6f57611f.png)

**Comment by VirusThePanda** [comment]
What version of Impression are you using? (This csn be found in the About section)

**Comment by mrbar42** [comment]
Impression 0.8.0

**Comment by M2ck** [comment]
See #322

**Comment by afollestad** [comment]
@mrbar42 read the F-Droid description, it says not to report bugs for that build to the upstream (this repository's build).
